---
title: "Estudo das relações das caractéristicas de um Parlamentar no Twitter"
author: "Igor Matheus Castor Diniz Pinheiro"
output:
    html_document:
      df_print: paged
      code_folding: hide
      toc: yes
      toc_depth: 5
      toc_float:
        collapsed: yes
    
theme: sandstone
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(broom)
library(here)
library(ggbeeswarm)
library(ggplot2)
library(gridExtra)
library(modelr)
library(tidyverse)
source(here("code/lib.R"))
options(scipen = 999)
theme_set(theme_bw())
```

```{r read}
apps = read_csv(here::here("data/googleplaystore.csv"))

apps = apps %>% 
  filter(Price != "Free" & Price != "0") %>% 
  mutate(double_price = extract_numeric(Price)) %>% 
  filter(!is.na(Rating))

apps
```

# 1. Qual a relação entre a avaliação e o número de reviews dos aplicativos da Google Play?

```{r}
apps %>% 
  ggplot(aes(x = Rating, y = Reviews)) +
  geom_quasirandom(size = 2, alpha = .7, colour = "orange")
```

```{r}
apps %>% 
  ggplot(aes(x = Rating, y = Reviews)) + 
  geom_quasirandom(size = 2, alpha = .7, colour = "orange") +
  scale_x_log10() +
  scale_y_log10()
```



## Criando o modelo

```{r}
apps = apps %>% 
  mutate(rating_log = log10(Rating)) %>% 
  mutate(reviews_log = log10(Reviews))
```


```{r}
modelo = lm(rating_log ~ reviews_log, 
   data = apps)

tidy(modelo)
glance(modelo)
```

## Conclusão
